  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api-app
  annotations:
spec:
  selector:
    matchLabels:
      app: api-app
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
      - name: api-app
        image: gabriellhuver/consumer-jvm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "256m"