  
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api-app
spec:
  type: LoadBalancer
  selector:
    app: api-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3030